version: "3.9"

services:

  fiware-orion:
    image: fiware/orion:latest
    container_name: fiware-orion
    ports:
      - "1026:1026"
    command:
      - "-dbURI"
      - "mongodb://mongo-db:27017"
      - "-logLevel"
      - "DEBUG"
    depends_on:
      - mongo-db
    networks:
      - fiware-net

  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo-db:/data
    networks:
      - fiware-net

  script-orion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: script-orion
    depends_on:
      - fiware-orion
      - mongo-db
    networks:
      - fiware-net
    restart: on-failure

networks:
  fiware-net:
    driver: bridge